---
- hosts: all
  tasks:

  - name: Create application user
    user:
      name: someuser

  - name: Set application user authorized_keys file
    authorized_key:
      user: someuser
      state: present
      key: "{{ lookup('file', playbook_dir + '/id_rsa.pub') }}"
